### PR TITLE
Add CI linting with clippy and rustfmt

### PR DESCRIPTION
**Pull request by nain-F49FF806**
This will automate rust formatting and code quality fixes.

### CODE REVIEW

**Comment by nain-F49FF806** [comment]
The second commit here is made automatically by the GitHub action.  The first commit defines the CI workflow for the same. 
You can see the workflow run here. [[workflow run](https://github.com/nain-F49FF806/pbcli/actions/runs/8499904461/job/23281199627)]

**Comment by Mydayyy** [comment]
Greetings,

I hope you are doing well.

Generally I am all in favor of extending the CICD Pipeline here, although I do believe that the CICD Pipeline issuing commits is an antipattern. What do you think about modifying the Pipeline so that it will only check the formatting and fail if the code is not properly formatted? Fixing it would then be up to the user.

Best Regards
Mydayyy

**Comment by nain-F49FF806** [comment]
Absolutely. That can be done. 
Just give me a min.

**Comment by nain-F49FF806** [comment]
Greetings, 

I have updated to only run the check and not issue automated commits. 
Should I also revert the already applied changes? Or do you want to keep them. 

Best Regards.

**Comment by Mydayyy** [comment]
Hey,

lets keep those, since I had that on my todo list anyways to let clippy do its clippy things. 

Best Regards
Mydayyy

**Comment by nain-F49FF806** [comment]
It should be good to go now. You may have a look. 
Cheers.

**Comment by nain-F49FF806** [comment]
Just a min. There's a little thing that needs fixing. 
Apologies.

**Comment by nain-F49FF806** [comment]
Greetings, 

This should now turn red on any unfixed Clippy warnings. So one can be alerted to fix them. 

Best Regards.

**Comment by nain-F49FF806** [comment]
Took care of all uncovered Clippy warnings. :upside_down_face:

**Comment by Mydayyy** [comment]
Merged, thanks for your contribution!

Best Regards
Mydayyy

**Comment by Mydayyy** [comment]
Did one quick fix on main, didn't catch that in the PR. Replaced main with master

**Pull request merged**
